//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sale
    {
        public int SaleID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
